name: zpc_test_AKMFNet_RSSCN7x2_pre_true
suffix: ~  # add suffix to saved images
model_type: JointModel
scale: 2
crop_border: ~  # crop border when evaluation. If None, crop the scale pixels
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 0

datasets:
  test:  # the 1st test dataset
    name: RSSCN7_test
    type: ThreeImageDataset
    dataroot_gt: /home/ubuntu/jointdatasets/RSSCN7/RSSCN7_test_HR
    dataroot_lr: /home/ubuntu/jointdatasets/RSSCN7/RSSCN7_test_LR_x2
    dataroot_lr_blur: /home/ubuntu/jointdatasets/RSSCN7/RSSCN7_test_LR_x2_motionblur
    io_backend:
      type: disk


# network structures
network_g:
  type: AKMF_Net

# path
path:
  pretrain_network_g: /home/ubuntu/projects/zpc/joint-De-SR/experiments/zpctrain_AKMFNet_Deblur-SR_RSSCN7x2_finish/models/net_g_latest.pth
  strict_load_g: true
  param_key_g: params

# validation settings
val:
  save_img: true
  suffix: ~  # add suffix to saved images, if None, use exp name
  metrics:
      psnr: # metric name, can be arbitrary
        type: calculate_psnr
        crop_border: 2
        test_y_channel: true
      ssim:
        type: calculate_ssim
        crop_border: 2
        test_y_channel: true