# general settings
name: zpctrain_AKMFNet_Deblur-SR_RSSCN7x2_pre_true
model_type: JointModel
scale: 2
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: RSSCN7_train
    type: ThreeImageDataset
    dataroot_gt: /home/ubuntu/jointdatasets/RSSCN7/RSSCN7_train_HR
    dataroot_lr: /home/ubuntu/jointdatasets/RSSCN7/RSSCN7_train_LR_x2
    dataroot_lr_blur: /home/ubuntu/jointdatasets/RSSCN7/RSSCN7_train_LR_x2_motionblur
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 17
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: RSSCN7_test
    type: ThreeImageDataset
    dataroot_gt: /home/ubuntu/jointdatasets/RSSCN7/RSSCN7_test_HR
    dataroot_lr: /home/ubuntu/jointdatasets/RSSCN7/RSSCN7_test_LR_x2
    dataroot_lr_blur: /home/ubuntu/jointdatasets/RSSCN7/RSSCN7_test_LR_x2_motionblur
    io_backend:
      type: disk

# network structures
network_g:
  type: AKMF_Net

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 8e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 115000, 300000, 400000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
